---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python3-pip

install:
  # Install applications needed
  - pip3 install ansible==2.10 molecule[docker] pytest-testinfra
  - ansible-galaxy collection install community.docker
  
  # Check ansible version
  - molecule --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  
  # Perform a molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
